### ISSUE TITLE
Can't rename members

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/flash-teams#155]
Need to be able to change the name of members. Currently, the name of the member is "read only" in the popover. 

![image](https://cloud.githubusercontent.com/assets/5275384/3122088/0a2c3096-e763-11e3-9b39-8466f4694e8f.png)

**Comment by ato1120** [comment]
Want to use Bootstrap editable Wysihtml5 to edit the names (Ex. at bottom of page http://vitalets.github.io/x-editable/demo.html?c=inline)

Don't want all of the edit features on that example (bold, text size, etc.)

*Only in bootstrap 2

**Comment by ato1120** [comment]
Roger closed!
