### ISSUE TITLE
Erasing an interaction prevents you from adding it again

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/flash-teams#156]
When you erase an interaction (e.g. a collaboration between two tasks), you get an error  if you try to add that same interaction again. See attached screenshot of error message.

![image](https://cloud.githubusercontent.com/assets/5275384/3125450/f734bd3c-e78a-11e3-9a0e-9bf554204a07.png)

**Comment by tdoshi** [comment]
Fixed!
