### ISSUE TITLE
Cannot Add Team Member to Existing Team

### ISSUE THREAD

**Issue by ato1120** [StanfordHCI/flash-teams#189]
When you return to edit an existing team and add a member, the member defaults to the blue color, unable to click on it. When you hit its delete (X) button, it deletes member number 1 or other earlier member when multiple 'bad new' members. 

Can add these 'bad new' members to events, but still cannot click them.

**Comment by dretelny** [comment]
Likely related to issue https://github.com/StanfordHCI/flash-startups/issues/181

**Comment by ato1120** [comment]
Notes: likely because pillCounter reset to 0 on page load!
