### ISSUE TITLE
Collaborations and Handoffs Complete

### ISSUE THREAD

**Issue by ato1120** [StanfordHCI/flash-teams#2]
Need to line-up with dragging
Need to invert the curve
Need to make clickable + Info Box
Need to make deletable

**Comment by dretelny** [comment]
Prevent duplicate collaborations (i.e. two events should only be allowed to have one collaboration), see attached screenshot

![image](https://f.cloud.github.com/assets/5275384/2162660/faf19dea-94d4-11e3-99ec-989caa7ff3ad.png)
