### ISSUE TITLE
Event popups are not connected with the member popups 

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/flash-teams#21]
Event popups do not disappear when you click on a member popup (see attached screenshot)

![image](https://f.cloud.github.com/assets/5275384/2162491/cc6b8d5c-94d2-11e3-9f2a-2a3a6496b575.png)

**Comment by ato1120** [comment]
Do we want this to happen? What if you want to look at the description of the task to edit the requirements for the member?

**Comment by dretelny** [comment]
Yes, you are right. Closing this issue since we aren't making this change.
